// src/lib/components/Chart.svelte
<script>
  import Chart from "chart.js";
  import { onMount } from "svelte";

  // @ts-ignore
  let chartCanvas;
  let chart;

  const renderChart = () => {
    // @ts-ignore
    chart = chartCanvas.getContext("2d");

    // NEW: there's acutally no error here so the line below gets rid of the red lines. try toggling it. so cool.
    //NOTE: i tried it here first before applying it to the ones above cause this one had more lines showing below it
    // @ts-ignore
    let myChart = new Chart(chart, {
      type: "radar",
      data: {
        labels: ["CSS/Sass", "Javascript", "Typescript", "Vue", "React", "Svelte", "Tailwind", "Bootstrap", "Gulp", "Webpack"],
        datasets: [
          {
            label: "Skill Levels",
            data: [84, 77, 49, 75, 45, 68, 60, 42, 60, 46],
            backgroundColor: "rgba(26, 41, 52, 0.5)",
          },
        ],
        borderColor: "red",
      },
      options: {
        scale: {
          ticks: {
            display: true,
            // Voila. I've found at how to get rid of that square background of the numbers. It's the backdropColor property under ticks, under options and you assign it a colour. I just did it to transparent
            //TODO: Make sure to add this in your chartjs learning repo.
            // * So glad I found it
            backdropColor: "transparent",
            fontColor: "rgba(26,41,52,0.6)",
            beginAtZero: true,
            max: 100,
          },
          pointLabels: {
            fontSize: 14, // fontSize is ok
            // don't know if i like it with or without
            //fontColor: "#1a2934", // fontColor is accessible
            fontFamily: "'Jost', 'sans-serif'",
          },
        },
      },
    });
  };

  onMount(() => {
    renderChart();
  });
</script>

<div class="proficiency__chart">
  <div class="proficiency__chart--container">
    <canvas bind:this={chartCanvas} id="myFirstChart" />
  </div>
</div>

<style lang="scss">
  .proficiency {
    &__chart {
      width: 125rem;
      //   height: 50rem;
      justify-self: center;

      &--container {
        position: relative;
        margin: 10rem 0;
        // margin-right: -8rem;
        width: 100%;
        grid-column: 1 / 2;
        grid-row: 2 / -1;
        //TESTING:
        height: 100%;

        // IMPORTANT class generated by chartjs that i found upon inspecting browser
        .chartjs-size-monitor {
          width: 100%;
          height: 100%;
        }

        #myFirstChart {
          display: block;
          width: 92rem;
          height: 47rem;
          height: 40%;
          height: 100%;
        }
      }
    }
  }
</style>

// components/shared/Chart.vue
<script setup>
import { BarChart as Bar } from "vue-chart-3";
import { Chart, registerables } from "chart.js";
Chart.register(...registerables);

const chartData = {
  labels: ["Sass", "Typescript", "Nuxt/Vue", "(Svelte)Kit", "PHP", "MongoDB", "Linux"],
  datasets: [
    {
      label: "Comfort Levels",
      data: [84, 66, 76, 70, 60, 55, 39],
      backgroundColor: [
        'rgb(205, 103, 153)',
        'rgb(35, 90, 151)',
        'rgb(66, 211, 146)',
        'rgb(255, 62, 0)',
        'rgb(137, 147, 190)',
        'rgb(0, 104, 74)',
        'rgb(255, 204, 51)'
      ],
      borderColor: [
        'rgb(205, 103, 153)',
        'rgb(35, 90, 151)',
        'rgb(66, 211, 146)',
        'rgb(255, 62, 0)',
        'rgb(137, 147, 190)',
        'rgb(0, 104, 74)',
        'rgb(255, 204, 51)'
      ],
      hoverBackgroundColor: [
        'rgba(205, 103, 153, 0.6)',
        'rgba(35, 90, 151, 0.6)',
        'rgba(66, 211, 146, 0.6)',
        'rgba(255, 62, 0, 0.6)',
        'rgba(137, 147, 190, 0.6)',
        'rgba(0, 104, 74, 0.6)',
        'rgba(255, 204, 51, 0.6)'
      ]
    },
  ],
}

const options = {
  plugins: {
    title: {
      display: true,
      text: 'Custom Chart Title',
      font: {
        size: 20,
        family: "Jost"
      }
    },
    subtitle: {
      display: true,
      text: 'Custom Chart Subtitle',
      padding: 14,
      font: {
        size: 14,
        family: "Jost"
      }
    },
    legend: {
      display: false
    },
  },
  scales: {
    x: {
      ticks: {
        font: {
          size: 20,
          family: "Jost"
        }
      }
    },
    y: {
      ticks: {
        font: {
          size: 20
        }
      }
    }
  },
}
</script>

<template>
  <Bar :chartData="chartData" :options="options" class="proficiency__chart" />
</template>

<style lang="scss">
// #line-chart {

// }

.proficiency {
  &__chart {
    // width: 100rem;
    height: 70dvh;
    grid-column: 1 / -1;
    grid-row: 2 / 3;
    padding: 4rem;
    // &--container {
    //   position: relative;
    //   margin: 10rem 0;
    //   // margin-right: -8rem;
    //   width: 100%;
    //   // grid-column: 1 / 3;
    //   // grid-row: 2 / -1;
    //   //TESTING:
    //   height: 100%;

    //   // IMPORTANT class generated by chartjs that i found upon inspecting browser
    //   .chartjs-size-monitor {
    //     width: 100%;
    //     height: 100%;
    //   }

    //   #myFirstChart {
    //     display: block;
    //     width: 92rem;
    //     height: 47rem;
    //     height: 40%;
    //     height: 100%;
    //   }
    // }
  }
}
</style>
