// src/lib/components/Frontend.svelte
<div class="front-end-container">
  <div class="skills__language lang-CSS">
    <div class="skills__language--x">
      <div style="display:flex">
        <i class="devicon-css3-plain" style="margin-right: 3rem" />
        <i class="devicon-sass-plain" style="margin-right: 3rem" />
        <i class="devicon-javascript-plain" style="margin-right: 3rem" />
      </div>
      <h5 class="skills__language-title">Vanilla Projects</h5>
    </div>
    <div class="skills__language--y">
      <ul class="skills__list">
        <li class="skills__list--item">
          Nu Renaissance
          <a href="https://gilberttsurwa-nurenaissance.netlify.app" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/gilberttsurwa-nu-renaissance-website" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Natours
          <a href="https://natours-gilberttsurwa-jonas.netlify.com" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/natours-jonas" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Omnifood
          <a href="https://omnifood-gilberttsurwa-jonas.netlify.com" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/omnifood-jonas" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Forkify
          <a href="https://gilberttsurwaforkifyproject.netlify.app/" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/forkify-app-jonas" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Nexter
          <a href="https://nexter-gilberttsurwa-jonas.netlify.com" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/nexter-jonas" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Colour Game
          <a href="https://colourgame-gilberttsurwa-colt.netlify.app" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/colourgame-app-colt" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="skills__language lang-React">
    <div class="skills__language--x">
      <i class="devicon-react-plain" />
      <h5 class="skills__language-title">React Projects</h5>
    </div>
    <div class="skills__language--y">
      <ul class="skills__list">
        <li class="skills__list--item">
          <span> Dad Jokes App <sup>Beta</sup> </span>
          <a href="https://piggame-gilberttsurwa-jonas.netlify.app/" target="__blank" class="">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/piggame-app-jonas" target="__blank" class="">
            <i class="devicon-github-plain" />
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="skills__language lang-Vue">
    <div class="skills__language--x">
      <div style="display:flex">
        <i class="devicon-vuejs-plain" />
        <i class="devicon-nuxtjs-plain" />
      </div>
      <h5 class="skills__language-title">Vue/Nuxt Projects</h5>
    </div>
    <div class="skills__language--y">
      <ul class="skills__list">
        <li class="skills__list--item">
          Mini Music Playlist
          <a href="https://gilberttsurwa-vue-music-player.netlify.app" target="__blank">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/vue-music-app" target="__blank">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Dad Jokes App
          <a href="https://gilberttsurwa-baba-jokes.netlify.app/" target="__blank">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/nuxt-with-brad-traversy" target="__blank">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          My Blog
          <a href="https://gilbertrabuttsurwa.blog/" target="__blank">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/nuxt-content-blog-app/" target="__blank">
            <i class="devicon-github-plain" />
          </a>
        </li>

        <li class="skills__list--item">
          Pokedex
          <a href="https://gilberttsurwa-pokedex-legacy.netlify.app/" target="__blank">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/nuxt-content-blog-app/" target="__blank">
            <i class="devicon-github-plain" />
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="skills__language lang-Svelte">
    <div class="skills__language--x">
      <i class="devicon-svelte-plain" />
      <h5 class="skills__language-title">Svelte/SvelteKit Projects</h5>
    </div>
    <div class="skills__language--y">
      <ul class="skills__list">
        <!-- <h4 style="font-size: 6rem">Coming Soon</h4> -->
        <!-- use this template when i have projects -->
        <li class="skills__list--item">
          Arch Studio Website
          <a href="https://gilberttsurwa-arch-studio.vercel.app/" target="__blank">
            <i class="devicon-devicon-plain" />
          </a>
          <a href="https://github.com/GillyRabutTsurwa/arch-studio-website" target="__blank">
            <i class="devicon-github-plain" />
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

<style lang="scss" scoped>
  .front-end-container {
    grid-column: 1 / -1;
    display: grid;
    gap: 4rem;
    grid-template-rows: repeat(2, 50rem);
  }
  .skills {
    &__language {
      position: relative;
      width: 100%;
      height: 100%;
      &-title {
        font-size: 1.7rem;
      }
      &:hover &--x {
        -webkit-filter: blur(1.2rem);
        filter: blur(1.2rem);
      }
      &:hover &--y {
        opacity: 1;
      }
      &--x,
      &--y {
        // ? QUESTION: ARE THESE NEEDED?
        position: absolute;
        top: 0;
        right: 0;
        width: 100%;
        height: 100%;
        // ? ==============================
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-transition: all 0.5s ease;
        transition: all 0.5s ease;
      }
      &--x {
        background-color: #1a2934;
        & i {
          font-size: 9rem;
        }
      }
      &--y {
        opacity: 0;
        z-index: 1000;
      }
      &.lang-CSS {
        grid-column: 1 / 2;
        grid-row: 1 / 2;
      }
      &.lang-React {
        grid-column: 1 / 2;
        grid-row: 2 / 3;
      }
      &.lang-Vue {
        grid-column: 2 / 3;
        grid-row: 1 / 2;
      }
      &.lang-Svelte {
        grid-column: 2 / 3;
        grid-row: 2 / 3;
      }
    }
    &__list {
      list-style: none;
      text-align: center;
      &--item {
        font-size: 3rem;
        span {
          position: relative; /* for beta sup element* */
          margin-right: 2rem;
          sup {
            position: absolute;
            right: -0.75rem;
            bottom: 2rem;
            font-size: 1rem;
            font-weight: bold;
          }
        }
        a {
          &:link,
          &:visited {
            color: rgb(238, 238, 238);
            -webkit-text-decoration: none;
            text-decoration: none;
          }
          &:hover,
          &:active {
            color: #fff;
            text-shadow: 0 0 5px #fff, 0 0 10px #fff, 2px 2px 2px rgba(206, 89, 55, 0);
          }
        }
      }
    }
  }
</style>

// components/home/FrontEnd.vue
<script setup>

</script>
<template>
  <div class="front-end-container">
    <div class="skills__language lang-CSS">
      <div class="skills__language--x">
        <div style="display:flex">
          <i class="devicon-css3-plain" style="margin-right: 3rem" />
          <i class="devicon-sass-plain" style="margin-right: 3rem" />
          <i class="devicon-javascript-plain" style="margin-right: 3rem" />
        </div>
        <h5 class="skills__language-title">Vanilla Projects</h5>
      </div>
      <div class="skills__language--y">
        <ul class="skills__list">
          <li class="skills__list--item">
            Nu Renaissance
            <a href="https://gilberttsurwa-nurenaissance.netlify.app" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/gilberttsurwa-nu-renaissance-website" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Natours
            <a href="https://natours-gilberttsurwa-jonas.netlify.com" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/natours-jonas" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Omnifood
            <a href="https://omnifood-gilberttsurwa-jonas.netlify.com" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/omnifood-jonas" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Forkify
            <a href="https://gilberttsurwaforkifyproject.netlify.app/" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/forkify-app-jonas" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Nexter
            <a href="https://nexter-gilberttsurwa-jonas.netlify.com" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/nexter-jonas" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Colour Game
            <a href="https://colourgame-gilberttsurwa-colt.netlify.app" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/colourgame-app-colt" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="skills__language lang-React">
      <div class="skills__language--x">
        <i class="devicon-react-plain" />
        <h5 class="skills__language-title">React Projects</h5>
      </div>
      <div class="skills__language--y">
        <ul class="skills__list">
          <li class="skills__list--item">
            <span> Dad Jokes App</span>
            <a href="https://piggame-gilberttsurwa-jonas.netlify.app/" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/piggame-app-jonas" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>
          <li class="skills__list--item">
            <span>Lights Out</span>
            <a href="https://gilberttsurwa-lightsout.vercel.app/" target="__blank" class="">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/lights-out-game" target="__blank" class="">
              <i class="devicon-github-plain" />
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="skills__language lang-Vue">
      <div class="skills__language--x">
        <div style="display:flex">
          <i class="devicon-vuejs-plain" />
          <i class="devicon-nuxtjs-plain" />
        </div>
        <h5 class="skills__language-title">Vue/Nuxt Projects</h5>
      </div>
      <div class="skills__language--y">
        <ul class="skills__list">
          <li class="skills__list--item">
            Mini Music Playlist
            <a href="https://gilberttsurwa-vue-music-player.netlify.app" target="__blank">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/vue-music-app" target="__blank">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Dad Jokes App
            <a href="https://gilberttsurwa-baba-jokes.netlify.app/" target="__blank">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/nuxt-with-brad-traversy" target="__blank">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            My Blog
            <a href="https://gilbertrabuttsurwa.blog/" target="__blank">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/nuxt-content-blog-app/" target="__blank">
              <i class="devicon-github-plain" />
            </a>
          </li>

          <li class="skills__list--item">
            Pokedex
            <a href="https://gilberttsurwa-pokedex-legacy.netlify.app/" target="__blank">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/nuxt-content-blog-app/" target="__blank">
              <i class="devicon-github-plain" />
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="skills__language lang-Svelte">
      <div class="skills__language--x">
        <i class="devicon-svelte-plain" />
        <h5 class="skills__language-title">Svelte/SvelteKit Projects</h5>
      </div>
      <div class="skills__language--y">
        <ul class="skills__list">
          <!-- <h4 style="font-size: 6rem">Coming Soon</h4> -->
          <!-- use this template when i have projects -->
          <li class="skills__list--item">
            Arch Studio Website
            <a href="https://gilberttsurwa-arch-studio.vercel.app/" target="__blank">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/arch-studio-website" target="__blank">
              <i class="devicon-github-plain" />
            </a>
          </li>
          <li class="skills__list--item">
            Jobs Dashboard
            <a href="https://jobs-dashboard-nu.vercel.app/" target="__blank">
              <i class="devicon-devicon-plain" />
            </a>
            <a href="https://github.com/GillyRabutTsurwa/jobs-dashboard" target="__blank">
              <i class="devicon-github-plain" />
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.front-end-container {
  grid-column: 1 / -1;
  display: grid;
  gap: 4rem;
  grid-template-rows: repeat(2, 50rem);

  @include breakpoint(1023) {
    grid-template-columns: 1fr;
    grid-template-rows: repeat(4, 50rem);
  }
}

.skills {
  &__language {
    position: relative;
    width: 100%;
    height: 100%;

    &-title {
      font-size: 1.7rem;
    }

    &:hover &--x {
      -webkit-filter: blur(1.2rem);
      filter: blur(1.2rem);
    }

    &:hover &--y {
      opacity: 1;
    }

    &--x,
    &--y {
      // ? QUESTION: ARE THESE NEEDED?
      position: absolute;
      top: 0;
      right: 0;
      width: 100%;
      height: 100%;
      // ? ==============================
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: vertical;
      -webkit-box-direction: normal;
      -ms-flex-direction: column;
      flex-direction: column;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      -webkit-transition: all 0.5s ease;
      transition: all 0.5s ease;
    }

    &--x {
      background-color: #1a2934;

      & i {
        font-size: 9rem;
        color: #f3f3f3;
      }
    }

    &--y {
      opacity: 0;
      z-index: 1000;

      & .skills__list {
        list-style: none;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;

        &--item {
          font-size: 3rem;
          display: flex;
          margin-bottom: 2rem;

          span {
            position: relative;
            /* for beta sup element* */
            margin-right: 2rem;

            sup {
              position: absolute;
              right: -0.75rem;
              bottom: 2rem;
              font-size: 1rem;
              font-weight: bold;
            }
          }

          a {

            // font-size: 4rem;
            &:link,
            &:visited {
              color: #eeeeee;
              -webkit-text-decoration: none;
              text-decoration: none;
            }

            &:hover,
            &:active {
              color: #eeeeee;
              text-shadow: 0 0 5px #fff, 0 0 10px #fff, 2px 2px 2px rgba(206, 89, 55, 0);
            }

            i {
              font-size: 4rem;
              color: #eee;
            }

          }
        }
      }
    }

    &.lang-CSS {
      grid-column: 1 / 2;
      grid-row: 1 / 2;
    }

    &.lang-React {
      grid-column: 1 / 2;
      grid-row: 2 / 3;
    }

    &.lang-Vue {
      grid-column: 2 / 3;
      grid-row: 1 / 2;

      @include breakpoint(1023) {
        grid-column: 1 / 2;
        grid-row: 3 / 4;
      }
    }

    &.lang-Svelte {
      grid-column: 2 / 3;
      grid-row: 2 / 3;

      @include breakpoint(1023) {
        grid-column: 1 / 2;
        grid-row: 4 / 5;
      }
    }
  }


}
</style>
